name: BACKEND Build & test THEN Sonar THEN Docker

on:
    # Trigger the workflow on push for the main branch
    # and pull request
    push:
        branches:
            - develop
        paths: 
            - 'back/**'
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main
        paths: 
            - 'back/**'
jobs:
    docker-backend:
        name: Image Docker back-end
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
    
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
    
          - name: Setting up Docker Buildx
            uses: docker/setup-buildx-action@v3
    
          - name: Build and push
            uses: docker/build-push-action@v5
            with:
              context: ./back
              file: ./back/Dockerfile
              push: true
              tags: floriancicd/bobapp:latest    
              
    
      
         
